### ISSUE TITLE
`anzu-query-replace-regexp` fails if replace target text contains `\` (?)

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [syohex/emacs-anzu#65]
I executed 

`M-x anzu-query-replace-regexp` 

by

`_\([a-z]\)` → `\,(upcase \1)`

then, error occurred

```
match-substitute-replacement: Invalid use of `\' in replacement text
```
Any suggestion ?

```
anzu version is anzu-20150928.1932
```

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue. Could you retry after updating latest version ? And could you tell me your Emacs version and your configuration(as possible as minimum) ?

![anzu](https://cloud.githubusercontent.com/assets/554281/10519100/45d9ae24-739f-11e5-9a18-56d8bc98fe0c.gif)

**Comment by Hiroyuki-Nagata** [comment]
@syohex 
I appreciate your help.
Just as you say, I tried to use `anzu 20151015.405`, then I can't reproduce this issue.

Probably, there is a difference between `anzu 20150928.1932` and `anzu 20151015.405`.

**Comment by jarvisschultz** [comment]
I'm having this same issue on the latest build `20161017.1607` whenever I try to re-use an already-entered regex. In other words, if I use the default regex from the previous invocation of `anzu-query-replace-regexp` or I use `M-n`/`M-p` to navigate the ring I get the same error as the OP. GIF below is an `emacs -Q` with minimal setup to load `anzu`. 

![output](https://user-images.githubusercontent.com/653487/45123915-0d076300-b12e-11e8-9e87-b2c8d0919dbe.gif)

+ GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
+ Ubuntu 18.04

**Comment by jarvisschultz** [comment]
Seems like the error can likely be fixed by adding a `query-replace-compile-replacment` call somewhere in [the definition of the `to` variable](https://github.com/syohex/emacs-anzu/blob/e6c56ca8b23ac433f7be58b6f3f50801dd4164e4/anzu.el#L767-L776) in `anzu--query-replace-common`. I can't quite grok what each of the conditions mean, but placing the conversion [directly in the call to `apply`](https://github.com/syohex/emacs-anzu/blob/e6c56ca8b23ac433f7be58b6f3f50801dd4164e4/anzu.el#L784-L785) as follows

```emacs-lisp
(apply #'perform-replace (anzu--construct-perform-replace-arguments
    from (query-replace-compile-replacement to t) delimited beg end backward query))
```
fixes the issue for navigating the ring of previous replacements, but unfortunately it breaks the default replacement and the interactive entering of replacements.
